CRUD Operation/PL/Controllers/DepartmentController.cs
using AutoMapper;
using BLL.Interfaces;
using BLL.Repositories;
using DAL.Entites;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PL.Models;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace PL.Controllers
{
	[Authorize]
	public class DepartmentController : Controller
    {
       
        private readonly IUnitOfWork unitOfWork;
        private readonly IMapper mapper;

        public DepartmentController(IUnitOfWork unitOfWork, IMapper mapper  )
        {
            this.unitOfWork = unitOfWork;
            this.mapper = mapper;
        }
        public async Task<IActionResult> Index(string SearchValue) 
        {
            if (string.IsNullOrEmpty(SearchValue))
            {
                var departments = mapper.Map<IEnumerable<Department>, IEnumerable<DepartmentViewModel>>(await unitOfWork.departmentRepository.GetAll());
                return View(departments);
            }
            else
            {
                var departments = mapper.Map<IEnumerable<Department>, IEnumerable<DepartmentViewModel>>(await unitOfWork.departmentRepository.SearchName(SearchValue));
                return View(departments);
            }
            
        }
        public IActionResult Create()
        {
            return  View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(DepartmentViewModel departmentViewModel )
        {
            if(ModelState.IsValid)
            {
              var department=mapper.Map<DepartmentViewModel,Department>(departmentViewModel);
                await unitOfWork.departmentRepository.Create(department);
                return RedirectToAction("Index");
            }
            return View(departmentViewModel);
        }
        public async Task<IActionResult> Details([FromRoute]int? Id,string viewName="Details")
        {
            if (Id == null)
                return NotFound();
            var department=await unitOfWork.departmentRepository.Get(Id);
            if (department== null)
                return NotFound();
            var departmentVM = mapper.Map<Department, DepartmentViewModel>(department);
            return View(viewName,departmentVM);
        }
        public async Task<IActionResult> Edit(int? Id)
        {
            return await Details(Id, "Edit");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute]int?Id,DepartmentViewModel departmentViewModel)
        {
            if (Id != departmentViewModel.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    var department=mapper.Map<DepartmentViewModel,Department>(departmentViewModel);
                   await  unitOfWork.departmentRepository.Update(department);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    return View(departmentViewModel);
                }
            }return View(departmentViewModel);
        }
        public async Task<IActionResult> Delete(int? Id)
        {
            return await Details(Id, "Delete");
        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute]int?Id,DepartmentViewModel departmentViewModel)
        {
            if (Id != departmentViewModel.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    var department = mapper.Map<DepartmentViewModel, Department>(departmentViewModel);
                   await unitOfWork.departmentRepository.Delete(department);
                    return RedirectToAction("Index");
                }
                catch(Exception ex)
                {

                    return View(departmentViewModel);
                }
            }
            return View(departmentViewModel);
        }
    }
}

CRUD Operation/PL/Controllers/EmployeeController.cs
using AutoMapper;
using BLL.Interfaces;
using BLL.Repositories;
using DAL.Entites;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PL.Helper;
using PL.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace PL.Controllers
{
	[Authorize]
	public class EmployeeController : Controller
    {
       
       
        private readonly IMapper mapper;

        public IUnitOfWork UnitOfWork { get; set; }

        public EmployeeController(IUnitOfWork unitOfWork,IMapper mapper)
        {
            
            this.UnitOfWork = unitOfWork; 
          
            this.mapper = mapper;
        }
        public async Task<IActionResult> Index(string SearchValue)
        {
            if (string.IsNullOrEmpty(SearchValue))
            {
                var employees = mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(await UnitOfWork.employeeRepository.GetAll());
                return View(employees);
            }
            else
            {
                var employees = mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(await UnitOfWork.employeeRepository.SearchName(SearchValue));
                return View(employees);
            }
        }
        public async Task<IActionResult> Create()
        {
            ViewBag.Departments=await UnitOfWork.departmentRepository.GetAll();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(EmployeeViewModel employeeVM)
        {
            if (ModelState.IsValid)
            {
                employeeVM.ImageName = DocumentSettings.UploadFile(employeeVM.Image, "Images"); 
                var employee=mapper.Map<EmployeeViewModel,Employee>(employeeVM);
              await UnitOfWork. employeeRepository.Create(employee);
                return RedirectToAction("Index");
            }
            ViewBag.Departments =await UnitOfWork.departmentRepository.GetAll();
            return View(employeeVM);
        }
        public async Task<IActionResult> Details([FromRoute] int? Id, string viewName = "Details")
        {
            if (Id == null)
                return NotFound();
            var Employee =await UnitOfWork.employeeRepository.Get(Id);
            if (Employee == null)
                return NotFound();
            var employeeVM=mapper.Map<Employee, EmployeeViewModel>(Employee);
            return View(viewName, employeeVM);
        }
        public async Task<IActionResult> Edit(int? Id)
        {
            ViewBag.Departments =await UnitOfWork.departmentRepository.GetAll();
            return await Details(Id, "Edit");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async  Task<IActionResult> Edit([FromRoute] int? Id, EmployeeViewModel employeeVM)
        {
            if (Id != employeeVM.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    var employee = mapper.Map<EmployeeViewModel, Employee>(employeeVM);
                   await UnitOfWork.employeeRepository.Update(employee);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    return View(employeeVM);
                }
            }
            ViewBag.Departments =await UnitOfWork.departmentRepository.GetAll();
            return View(employeeVM);
        }
        public async Task<IActionResult> Delete(int? Id)
        {
            return await Details(Id, "Delete");
        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] int? Id, EmployeeViewModel EmployeeVM)
        {
            if (Id != EmployeeVM.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    
                    var employee = mapper.Map<EmployeeViewModel, Employee>(EmployeeVM);
                    DocumentSettings.DeleteFile(employee.ImageName, "Images");
                    await  UnitOfWork.employeeRepository.Delete(employee);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {

                    return View(EmployeeVM);
                }
            }
            return View(EmployeeVM);
        }

    }
}

CRUD Operation/PL/Controllers/UsersController.cs
using AutoMapper;
using BLL.Interfaces;
using BLL.Repositories;
using DAL.Entites;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PL.Helper;
using PL.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace PL.Controllers
{
	[Authorize]
	public class UsersController : Controller
	{
		private readonly UserManager<ApplicationUser> userManager;
		private readonly SignInManager<ApplicationUser> signInManager;

		public UsersController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
		{
			this.userManager = userManager;
			this.signInManager = signInManager;
		}
		public async Task<IActionResult> Index(string SearchValue)
		{
			if (string.IsNullOrEmpty(SearchValue))
				return View(userManager.Users);

			else
			{
				var user = await userManager.FindByEmailAsync(SearchValue);
				if (user == null)
                    return View(userManager.Users);
                return View(new List<ApplicationUser>() { user });
			}
		}

		public async Task<IActionResult> Details([FromRoute] string Id, string viewName = "Details")
		{
			if (Id == null)
				return NotFound();
			var user = await userManager.FindByIdAsync(Id);
			if (user == null)
				return NotFound();
			return View(viewName, user);
		}
		public async Task<IActionResult> Edit(string Id)
		{

			return await Details(Id, "Edit");
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit([FromRoute] string Id, ApplicationUser updatedUser)
		{
			if (Id != updatedUser.Id)
				return BadRequest();
			if (ModelState.IsValid)
			{
				try
				{
					var user = await userManager.FindByIdAsync(Id);
					user.UserName = updatedUser.UserName;
					user.NormalizedEmail = updatedUser.NormalizedEmail;
					user.PhoneNumber = updatedUser.PhoneNumber;
					var result = await userManager.UpdateAsync(user);
					return RedirectToAction("Index");
				}
				catch (Exception ex)
				{
					throw;
				}
			}

			return View(updatedUser);
		}
		public async Task<IActionResult> Delete(string Id)
		{
			return await Details(Id, "Delete");
		}
		[HttpPost]
		public async Task<IActionResult> Delete([FromRoute] string Id, ApplicationUser deletedUser)
		{
			if (Id != deletedUser.Id)
				return BadRequest();
			if (ModelState.IsValid)
			{
				try
				{
					var user= await userManager.FindByIdAsync(deletedUser.Id);
					var result = await userManager.DeleteAsync(user);
					if (result.Succeeded)
						return RedirectToAction("Index");

					foreach (var error in result.Errors)
						ModelState.AddModelError(string.Empty, error.Description);
					return View(deletedUser);
				}
				catch (Exception ex)
				{
					throw;
				}
			}
			return View(deletedUser);
		}

	}
}

CRUD Operation/PL/Views/Shared/AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
<title>@ViewData["Title"]</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Custom Theme files -->
<link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
<!-- //Custom Theme files -->
<!-- web font -->
<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>@ViewData["Title"]</h1>
		@RenderBody()
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2023 </p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
</body>
</html>

CRUD Operation/PL/Views/Shared/ButtonsParitialView.cshtml
@model string

<td class="align-middle">
    <a asp-action="Details" asp-controller="Employee" class="btn btn-success" asp-route-id="@Model">
        <i class="fas fa-eye"></i>  Details
    </a>
</td>
<td class="align-middle">
    <a asp-action="Edit" asp-controller="Employee" class="btn btn-warning" asp-route-id="@Model">
        <i class="fas fa-edit"></i>  Update
    </a>
</td>
<td class="align-middle">
    <a asp-action="Delete" asp-controller="Employee" class="btn btn-danger" asp-route-id="@Model">
        <i class="fas fa-trash"></i>  Delete
    </a>
</td>

CRUD Operation/PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Depratments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">LogIn</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("scriptsection", required: false)
</body>
</html>